version: 0.0.{build}
os: Visual Studio 2015
platform: Win32
configuration: Release
build:
  project: src\CaulsCastle.sln
  verbosity: minimal
after_build:
- ps: >-
    # Get-ChildItem "lib" *.dll -Recurse | ?{-not ($_.PSIsContainer -or (Test-Path "src\Debug\$_"))} | Copy-Item -Destination "src\Debug"

    # Copy-Item samples src\Debug -recurse

    New-Item out -type directory

    Move-Item assets out

    Move-Item src\Release out\bin

    Move-Item Start.bat out
artifacts:
- path: out
  name: CaulsCastle
