version: 0.0.{build}
os: Visual Studio 2015
platform: Win32
configuration: Release
build:
  project: src\CaulsCastle.sln
  verbosity: minimal
after_build:
- ps: >-
    # Get-ChildItem "lib" *.dll -Recurse | ?{-not ($_.PSIsContainer -or (Test-Path "src\Debug\$_"))} | Copy-Item -Destination "src\Debug"

    Move-Item assets src\Release

    Move-Item Start.bat src\Release

    # Copy-Item samples src\Debug -recurse

    Move-Item src\Release .\bin
artifacts:
- path: bin
  name: CaulsCastle
